# Generated by Django 5.0.3 on 2024-08-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habitacion',
            new_name='habitaciones',
        ),
    ]
