# Generated by Django 5.0.3 on 2024-08-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='habitaciones',
        ),
    ]
